version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=development
      - PERSISTENCE=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
